target 'arena-CodeChallenge' do

  pod "AFNetworking"
  pod "Mantle"
  pod "SDWebImage"
  pod "MBProgressHUD"

  target 'arena-CodeChallengeTests' do
    inherit! :search_paths
    pod "Specta"
    pod "Expecta"
  end


end
